package OTS.DataModels;
// Generated Jan 28, 2016 10:02:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Academiccourse generated by hbm2java
 */
public class Academiccourse  implements java.io.Serializable {


     private Integer courseTypeId;
     private String number;
     private String name;
     private String description;
     private Set teachercoursetests = new HashSet(0);
     private Set studentcourseregistrations = new HashSet(0);
     private Set courseassignments = new HashSet(0);
     private Set studenttests = new HashSet(0);

    public Academiccourse() {
    }

    public Academiccourse(String number, String name, String description, Set teachercoursetests, Set studentcourseregistrations, Set courseassignments, Set studenttests) {
       this.number = number;
       this.name = name;
       this.description = description;
       this.teachercoursetests = teachercoursetests;
       this.studentcourseregistrations = studentcourseregistrations;
       this.courseassignments = courseassignments;
       this.studenttests = studenttests;
    }
   
    public Integer getCourseTypeId() {
        return this.courseTypeId;
    }
    
    public void setCourseTypeId(Integer courseTypeId) {
        this.courseTypeId = courseTypeId;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTeachercoursetests() {
        return this.teachercoursetests;
    }
    
    public void setTeachercoursetests(Set teachercoursetests) {
        this.teachercoursetests = teachercoursetests;
    }
    public Set getStudentcourseregistrations() {
        return this.studentcourseregistrations;
    }
    
    public void setStudentcourseregistrations(Set studentcourseregistrations) {
        this.studentcourseregistrations = studentcourseregistrations;
    }
    public Set getCourseassignments() {
        return this.courseassignments;
    }
    
    public void setCourseassignments(Set courseassignments) {
        this.courseassignments = courseassignments;
    }
    public Set getStudenttests() {
        return this.studenttests;
    }
    
    public void setStudenttests(Set studenttests) {
        this.studenttests = studenttests;
    }




}


