package OTS.DataModels;
// Generated 6-Feb-2016 4:41:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Courseassignment generated by hbm2java
 */
public class Courseassignment  implements java.io.Serializable {


     private CourseassignmentId id;
     private Academiccourse academiccourse;
     private Date assignOn;
     private Date endDate;
     private Boolean isCompleted;

    public Courseassignment() {
    }

	
    public Courseassignment(CourseassignmentId id, Academiccourse academiccourse) {
        this.id = id;
        this.academiccourse = academiccourse;
    }
    public Courseassignment(CourseassignmentId id, Academiccourse academiccourse, Date assignOn, Date endDate, Boolean isCompleted) {
       this.id = id;
       this.academiccourse = academiccourse;
       this.assignOn = assignOn;
       this.endDate = endDate;
       this.isCompleted = isCompleted;
    }
   
    public CourseassignmentId getId() {
        return this.id;
    }
    
    public void setId(CourseassignmentId id) {
        this.id = id;
    }
    public Academiccourse getAcademiccourse() {
        return this.academiccourse;
    }
    
    public void setAcademiccourse(Academiccourse academiccourse) {
        this.academiccourse = academiccourse;
    }
    public Date getAssignOn() {
        return this.assignOn;
    }
    
    public void setAssignOn(Date assignOn) {
        this.assignOn = assignOn;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Boolean getIsCompleted() {
        return this.isCompleted;
    }
    
    public void setIsCompleted(Boolean isCompleted) {
        this.isCompleted = isCompleted;
    }




}


