package OTS.DataModels;
// Generated Dec 20, 2014 11:09:02 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Courseregistration generated by hbm2java
 */
public class Courseregistration  implements java.io.Serializable {


     private CourseregistrationId id;
     private Academiccourse academiccourse;
     private Date date;
     private String grade;
     private Boolean isCompleted;

    public Courseregistration() {
    }

	
    public Courseregistration(CourseregistrationId id, Academiccourse academiccourse) {
        this.id = id;
        this.academiccourse = academiccourse;
    }
    public Courseregistration(CourseregistrationId id, Academiccourse academiccourse, Date date, String grade, Boolean isCompleted) {
       this.id = id;
       this.academiccourse = academiccourse;
       this.date = date;
       this.grade = grade;
       this.isCompleted = isCompleted;
    }
   
    public CourseregistrationId getId() {
        return this.id;
    }
    
    public void setId(CourseregistrationId id) {
        this.id = id;
    }
    public Academiccourse getAcademiccourse() {
        return this.academiccourse;
    }
    
    public void setAcademiccourse(Academiccourse academiccourse) {
        this.academiccourse = academiccourse;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getGrade() {
        return this.grade;
    }
    
    public void setGrade(String grade) {
        this.grade = grade;
    }
    public Boolean getIsCompleted() {
        return this.isCompleted;
    }
    
    public void setIsCompleted(Boolean isCompleted) {
        this.isCompleted = isCompleted;
    }




}


