package OTS.DataModels;
// Generated 6-Feb-2016 4:41:34 PM by Hibernate Tools 4.3.1



/**
 * CourseassignmentId generated by hbm2java
 */
public class CourseassignmentId  implements java.io.Serializable {


     private int teacherId;
     private int courseId;

    public CourseassignmentId() {
    }

    public CourseassignmentId(int teacherId, int courseId) {
       this.teacherId = teacherId;
       this.courseId = courseId;
    }
   
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CourseassignmentId) ) return false;
		 CourseassignmentId castOther = ( CourseassignmentId ) other; 
         
		 return (this.getTeacherId()==castOther.getTeacherId())
 && (this.getCourseId()==castOther.getCourseId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTeacherId();
         result = 37 * result + this.getCourseId();
         return result;
   }   


}


