package OTS.DataModels;
// Generated Dec 20, 2014 11:09:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departmenttype generated by hbm2java
 */
public class Departmenttype  implements java.io.Serializable {


     private Integer departmentTypeId;
     private String name;
     private String description;
     private Set users = new HashSet(0);

    public Departmenttype() {
    }

    public Departmenttype(String name, String description, Set users) {
       this.name = name;
       this.description = description;
       this.users = users;
    }
   
    public Integer getDepartmentTypeId() {
        return this.departmentTypeId;
    }
    
    public void setDepartmentTypeId(Integer departmentTypeId) {
        this.departmentTypeId = departmentTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


