package OTS.DataModels;
// Generated 6-Feb-2016 4:41:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Knowledgemap generated by hbm2java
 */
public class Knowledgemap  implements java.io.Serializable {


     private Integer knowledgeMapId;
     private User user;
     private String name;
     private String description;
     private Date createOn;
     private String concepts;
     private Date lastUpdated;
     private Boolean isPublic;

    public Knowledgemap() {
    }

	
    public Knowledgemap(String name, Date createOn) {
        this.name = name;
        this.createOn = createOn;
    }
    public Knowledgemap(User user, String name, String description, Date createOn, String concepts, Date lastUpdated, Boolean isPublic) {
       this.user = user;
       this.name = name;
       this.description = description;
       this.createOn = createOn;
       this.concepts = concepts;
       this.lastUpdated = lastUpdated;
       this.isPublic = isPublic;
    }
   
    public Integer getKnowledgeMapId() {
        return this.knowledgeMapId;
    }
    
    public void setKnowledgeMapId(Integer knowledgeMapId) {
        this.knowledgeMapId = knowledgeMapId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreateOn() {
        return this.createOn;
    }
    
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }
    public String getConcepts() {
        return this.concepts;
    }
    
    public void setConcepts(String concepts) {
        this.concepts = concepts;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
    public Boolean getIsPublic() {
        return this.isPublic;
    }
    
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }




}


