package OTS.DataModels;
// Generated Feb 3, 2016 3:28:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Questiontype generated by hbm2java
 */
public class Questiontype  implements java.io.Serializable {


     private Integer questionType;
     private String name;
     private Set testitems = new HashSet(0);
     private Set questions = new HashSet(0);

    public Questiontype() {
    }

    public Questiontype(String name, Set testitems, Set questions) {
       this.name = name;
       this.testitems = testitems;
       this.questions = questions;
    }
   
    public Integer getQuestionType() {
        return this.questionType;
    }
    
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTestitems() {
        return this.testitems;
    }
    
    public void setTestitems(Set testitems) {
        this.testitems = testitems;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }




}


