package OTS.DataModels;
// Generated Feb 4, 2016 2:42:16 PM by Hibernate Tools 4.3.1



/**
 * Questionlineitem generated by hbm2java
 */
public class Questionlineitem  implements java.io.Serializable {


     private Integer questionLineItemId;
     private Question question;
     private String text;
     private Boolean isCorrect;

    public Questionlineitem() {
    }

    public Questionlineitem(Question question, String text, Boolean isCorrect) {
       this.question = question;
       this.text = text;
       this.isCorrect = isCorrect;
    }
   
    public Integer getQuestionLineItemId() {
        return this.questionLineItemId;
    }
    
    public void setQuestionLineItemId(Integer questionLineItemId) {
        this.questionLineItemId = questionLineItemId;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Boolean getIsCorrect() {
        return this.isCorrect;
    }
    
    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }




}


