package OTS.DataModels;
// Generated Jan 28, 2016 10:02:56 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private Integer questionId;
     private Cognitiveleveltype cognitiveleveltype;
     private Questionnaturetype questionnaturetype;
     private Questiontype questiontype;
     private String text;
     private Float mark;
     private Set questionlineitems = new HashSet(0);
     private Set answers = new HashSet(0);

    public Question() {
    }

    public Question(Cognitiveleveltype cognitiveleveltype, Questionnaturetype questionnaturetype, Questiontype questiontype, String text, Float mark, Set questionlineitems, Set answers) {
       this.cognitiveleveltype = cognitiveleveltype;
       this.questionnaturetype = questionnaturetype;
       this.questiontype = questiontype;
       this.text = text;
       this.mark = mark;
       this.questionlineitems = questionlineitems;
       this.answers = answers;
    }
   
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public Cognitiveleveltype getCognitiveleveltype() {
        return this.cognitiveleveltype;
    }
    
    public void setCognitiveleveltype(Cognitiveleveltype cognitiveleveltype) {
        this.cognitiveleveltype = cognitiveleveltype;
    }
    public Questionnaturetype getQuestionnaturetype() {
        return this.questionnaturetype;
    }
    
    public void setQuestionnaturetype(Questionnaturetype questionnaturetype) {
        this.questionnaturetype = questionnaturetype;
    }
    public Questiontype getQuestiontype() {
        return this.questiontype;
    }
    
    public void setQuestiontype(Questiontype questiontype) {
        this.questiontype = questiontype;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Float getMark() {
        return this.mark;
    }
    
    public void setMark(Float mark) {
        this.mark = mark;
    }
    public Set getQuestionlineitems() {
        return this.questionlineitems;
    }
    
    public void setQuestionlineitems(Set questionlineitems) {
        this.questionlineitems = questionlineitems;
    }
    public Set getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set answers) {
        this.answers = answers;
    }




}


