package OTS.DataModels;
// Generated Jan 28, 2016 10:02:56 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Studentcourseregistration generated by hbm2java
 */
public class Studentcourseregistration  implements java.io.Serializable {


     private Integer studentCourseId;
     private Academiccourse academiccourse;
     private User user;
     private Date date;

    public Studentcourseregistration() {
    }

	
    public Studentcourseregistration(Academiccourse academiccourse, User user) {
        this.academiccourse = academiccourse;
        this.user = user;
    }
    public Studentcourseregistration(Academiccourse academiccourse, User user, Date date) {
       this.academiccourse = academiccourse;
       this.user = user;
       this.date = date;
    }
   
    public Integer getStudentCourseId() {
        return this.studentCourseId;
    }
    
    public void setStudentCourseId(Integer studentCourseId) {
        this.studentCourseId = studentCourseId;
    }
    public Academiccourse getAcademiccourse() {
        return this.academiccourse;
    }
    
    public void setAcademiccourse(Academiccourse academiccourse) {
        this.academiccourse = academiccourse;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


