package OTS.DataModels;
// Generated Feb 4, 2016 2:42:16 PM by Hibernate Tools 4.3.1



/**
 * Studenttestanswersheet generated by hbm2java
 */
public class Studenttestanswersheet  implements java.io.Serializable {


     private Integer studentTestAnswerSheetId;
     private Test test;
     private Testitem testitem;
     private User user;
     private Boolean a;
     private Boolean b;
     private Boolean c;
     private Boolean d;
     private Boolean isCorrect;
     private Integer totalCorrectAnswers;

    public Studenttestanswersheet() {
    }

	
    public Studenttestanswersheet(Test test, Testitem testitem, User user) {
        this.test = test;
        this.testitem = testitem;
        this.user = user;
    }
    public Studenttestanswersheet(Test test, Testitem testitem, User user, Boolean a, Boolean b, Boolean c, Boolean d, Boolean isCorrect, Integer totalCorrectAnswers) {
       this.test = test;
       this.testitem = testitem;
       this.user = user;
       this.a = a;
       this.b = b;
       this.c = c;
       this.d = d;
       this.isCorrect = isCorrect;
       this.totalCorrectAnswers = totalCorrectAnswers;
    }
   
    public Integer getStudentTestAnswerSheetId() {
        return this.studentTestAnswerSheetId;
    }
    
    public void setStudentTestAnswerSheetId(Integer studentTestAnswerSheetId) {
        this.studentTestAnswerSheetId = studentTestAnswerSheetId;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public Testitem getTestitem() {
        return this.testitem;
    }
    
    public void setTestitem(Testitem testitem) {
        this.testitem = testitem;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Boolean getA() {
        return this.a;
    }
    
    public void setA(Boolean a) {
        this.a = a;
    }
    public Boolean getB() {
        return this.b;
    }
    
    public void setB(Boolean b) {
        this.b = b;
    }
    public Boolean getC() {
        return this.c;
    }
    
    public void setC(Boolean c) {
        this.c = c;
    }
    public Boolean getD() {
        return this.d;
    }
    
    public void setD(Boolean d) {
        this.d = d;
    }
    public Boolean getIsCorrect() {
        return this.isCorrect;
    }
    
    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }
    public Integer getTotalCorrectAnswers() {
        return this.totalCorrectAnswers;
    }
    
    public void setTotalCorrectAnswers(Integer totalCorrectAnswers) {
        this.totalCorrectAnswers = totalCorrectAnswers;
    }




}


