package OTS.DataModels;
// Generated Feb 3, 2016 3:28:45 PM by Hibernate Tools 4.3.1



/**
 * Testitemoption generated by hbm2java
 */
public class Testitemoption  implements java.io.Serializable {


     private Integer testItemOptionId;
     private Testitem testitem;
     private String text;
     private Boolean isCorrect;

    public Testitemoption() {
    }

    public Testitemoption(Testitem testitem, String text, Boolean isCorrect) {
       this.testitem = testitem;
       this.text = text;
       this.isCorrect = isCorrect;
    }
   
    public Integer getTestItemOptionId() {
        return this.testItemOptionId;
    }
    
    public void setTestItemOptionId(Integer testItemOptionId) {
        this.testItemOptionId = testItemOptionId;
    }
    public Testitem getTestitem() {
        return this.testitem;
    }
    
    public void setTestitem(Testitem testitem) {
        this.testitem = testitem;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Boolean getIsCorrect() {
        return this.isCorrect;
    }
    
    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }




}


