package OTS.DataModels;
// Generated 6-Feb-2016 4:41:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private Integer testId;
     private String name;
     private Float totalMark;
     private Integer numberOfQuestion;
     private Date startDate;
     private String startTime;
     private String endTime;
     private Boolean isActivated;
     private Set teachercoursetests = new HashSet(0);
     private Set testitems = new HashSet(0);
     private Set studenttests = new HashSet(0);
     private Set questions = new HashSet(0);
     private Set studenttestanswersheets = new HashSet(0);
     private Set testanswersheets = new HashSet(0);

    public Test() {
    }

    public Test(String name, Float totalMark, Integer numberOfQuestion, Date startDate, String startTime, String endTime, Boolean isActivated, Set teachercoursetests, Set testitems, Set studenttests, Set questions, Set studenttestanswersheets, Set testanswersheets) {
       this.name = name;
       this.totalMark = totalMark;
       this.numberOfQuestion = numberOfQuestion;
       this.startDate = startDate;
       this.startTime = startTime;
       this.endTime = endTime;
       this.isActivated = isActivated;
       this.teachercoursetests = teachercoursetests;
       this.testitems = testitems;
       this.studenttests = studenttests;
       this.questions = questions;
       this.studenttestanswersheets = studenttestanswersheets;
       this.testanswersheets = testanswersheets;
    }
   
    public Integer getTestId() {
        return this.testId;
    }
    
    public void setTestId(Integer testId) {
        this.testId = testId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getTotalMark() {
        return this.totalMark;
    }
    
    public void setTotalMark(Float totalMark) {
        this.totalMark = totalMark;
    }
    public Integer getNumberOfQuestion() {
        return this.numberOfQuestion;
    }
    
    public void setNumberOfQuestion(Integer numberOfQuestion) {
        this.numberOfQuestion = numberOfQuestion;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public String getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }
    public String getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
    public Boolean getIsActivated() {
        return this.isActivated;
    }
    
    public void setIsActivated(Boolean isActivated) {
        this.isActivated = isActivated;
    }
    public Set getTeachercoursetests() {
        return this.teachercoursetests;
    }
    
    public void setTeachercoursetests(Set teachercoursetests) {
        this.teachercoursetests = teachercoursetests;
    }
    public Set getTestitems() {
        return this.testitems;
    }
    
    public void setTestitems(Set testitems) {
        this.testitems = testitems;
    }
    public Set getStudenttests() {
        return this.studenttests;
    }
    
    public void setStudenttests(Set studenttests) {
        this.studenttests = studenttests;
    }
    public Set getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set questions) {
        this.questions = questions;
    }
    public Set getStudenttestanswersheets() {
        return this.studenttestanswersheets;
    }
    
    public void setStudenttestanswersheets(Set studenttestanswersheets) {
        this.studenttestanswersheets = studenttestanswersheets;
    }
    public Set getTestanswersheets() {
        return this.testanswersheets;
    }
    
    public void setTestanswersheets(Set testanswersheets) {
        this.testanswersheets = testanswersheets;
    }




}


