package OTS.DataModels;
// Generated 12-Jul-2015 3:34:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Testsheet generated by hbm2java
 */
public class Testsheet  implements java.io.Serializable {


     private Integer testSheetId;
     private Question question;
     private Test test;
     private Integer lineNumber;
     private Set testsheetansweroptions = new HashSet(0);

    public Testsheet() {
    }

	
    public Testsheet(Question question, Test test) {
        this.question = question;
        this.test = test;
    }
    public Testsheet(Question question, Test test, Integer lineNumber, Set testsheetansweroptions) {
       this.question = question;
       this.test = test;
       this.lineNumber = lineNumber;
       this.testsheetansweroptions = testsheetansweroptions;
    }
   
    public Integer getTestSheetId() {
        return this.testSheetId;
    }
    
    public void setTestSheetId(Integer testSheetId) {
        this.testSheetId = testSheetId;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public Integer getLineNumber() {
        return this.lineNumber;
    }
    
    public void setLineNumber(Integer lineNumber) {
        this.lineNumber = lineNumber;
    }
    public Set getTestsheetansweroptions() {
        return this.testsheetansweroptions;
    }
    
    public void setTestsheetansweroptions(Set testsheetansweroptions) {
        this.testsheetansweroptions = testsheetansweroptions;
    }




}


