package OTS.DataModels;
// Generated 6-Feb-2016 4:41:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usertype generated by hbm2java
 */
public class Usertype  implements java.io.Serializable {


     private Integer userTypeId;
     private String name;
     private String homePageName;
     private Set users = new HashSet(0);

    public Usertype() {
    }

    public Usertype(String name, String homePageName, Set users) {
       this.name = name;
       this.homePageName = homePageName;
       this.users = users;
    }
   
    public Integer getUserTypeId() {
        return this.userTypeId;
    }
    
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getHomePageName() {
        return this.homePageName;
    }
    
    public void setHomePageName(String homePageName) {
        this.homePageName = homePageName;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


